[package]
name = "quicknote"
version = "0.1.0"
description = "Une note unique et permanente, affichée par un raccourci global"
authors = ["Axel Leclercq"]
edition = "2021"

[lib]
name = "quicknote_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
